---
- hosts: all
  become: true
  tasks:
    - name: "Update, upgrade, and restart instance"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/base-update-upgrade-reboot.yml"

    - name: "Install containerd"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/base-install-containerd.yml"

    - name: "Install Kubernetes"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/base-install-kubernetes.yml"
