---
- hosts: all
  become: true
  tasks:
    - name: "Setup Kubernetes on control node"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/control-setup-kubernetes.yml"

    - name: "Setup Helm on control node"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/control-setup-helm.yml"

    - name: "Generate join command on control node"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/control-generate-join.yml"
