---
- hosts: all
  become: true
  tasks:
    - name: "Run join command on worker nodes"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/worker-join.yml"
      tags: ["worker", "join"]
