---
- hosts: all
  become: true
  tasks:
    - name: "Install containerd"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/common-install-containerd.yml"

    - name: "Install Kubernetes"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/common-install-kubernetes.yml"

    - name: "Run join command on worker nodes"
      ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/worker-join.yml"
