---
- hosts: all
  become: true
  tasks:
    - name: "Disable swap"
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/includes/common-disable-swap.yml"

    - name: "Run join command on worker nodes"
      ansible.builtin.include_tasks: "{{ playbook_dir }}/includes/minion-join.yml"
