- name: Generate join command
  ansible.builtin.shell: kubeadm token create --print-join-command 2>/dev/null > /tmp/k8s-join.sh
  changed_when: join_command.rc != 0
  register: join_command

- name: Copy join command to worker nodes
  synchronize:
    src: /tmp/k8s-join.sh
    dest: /tmp/k8s-join.sh
    mode: push
    use_ssh_args: true
  delegate_to: k8s-control
