- name: Generate join command
  ansible.builtin.shell: kubeadm token create --print-join-command 2>/dev/null > /tmp/k8s-join.sh
  changed_when: join_command.rc != 0
  register: join_command

- name: Fetch /tmp/k8s-join.sh from control node to local
  fetch:
    src: /tmp/k8s-join.sh
    dest: ./k8s-join.sh 
    flat: true
