- name: Determine if the Kubernetes cluster is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_initialized

- name: Initialize the Kubernetes cluster using kubeadm
  when: not k8s_initialized.stat.exists
  ansible.builtin.command: >
    kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    --apiserver-cert-extra-sans="k8s-control"
    --pod-network-cidr="{{ pod_network_cidr }}"

- name: Create .kube directory for vagrant user
  when: not k8s_initialized.stat.exists
  ansible.builtin.file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode: "0755"

- name: Create .kube directory for root user
  when: not k8s_initialized.stat.exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: "0755"

- name: Copy admin.conf to vagrant user's kubeconfig
  when: not k8s_initialized.stat.exists
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: true
    owner: vagrant
    group: vagrant
    mode: "0600"

- name: Copy admin.conf to root user's kubeconfig
  when: not k8s_initialized.stat.exists
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: "0600"

- name: Wait for Kubernetes API server to be ready
  when: not k8s_initialized.stat.exists
  ansible.builtin.command: kubectl --kubeconfig=/etc/kubernetes/admin.conf get nodes
  register: api_status
  until: api_status.rc == 0
  retries: 30
  delay: 5

- name: Install Flannel network plugin
  when: not k8s_initialized.stat.exists
  ansible.builtin.command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  register: flannel_result
  changed_when: flannel_result.rc == 0

- name: Wait for Flannel pods to be ready
  when: not k8s_initialized.stat.exists
  ansible.builtin.command: kubectl --kubeconfig=/etc/kubernetes/admin.conf wait --namespace=kube-flannel --for=condition=ready pod --selector=app=flannel --timeout=60s
  register: flannel_wait
  until: flannel_wait.rc == 0
  retries: 30
  delay: 5
