- name: Generate join command
  ansible.builtin.shell: kubeadm token create --print-join-command 2>/dev/null > /tmp/join
  changed_when: join_command.rc != 0
  register: join_command

- name: Copy join command to local file
  ansible.builtin.fetch:
    src: /tmp/join
    dest: /tmp/join
    flat: True
